# kitty config, matching the foot setup
include pistachio-noir.conf

font_family          family="Terminess Nerd Font" style="Regular"
bold_font            family="Terminess Nerd Font" style="Regular"
bold_italic_font     auto
font_size            14.0

window_padding_width 8
cursor_shape         beam
enable_audio_bell    no
