
font=Terminess Nerd Font:size=14

pad=12x12 center-when-maximized-and-fullscreen

[bell]
notify=no

[cursor]
style=beam

[colors-dark]
background=15170F
foreground=E5E9D8
 
## regular (0-7)
regular0=1D2016   # black
regular1=DB8267   # red
regular2=9FD88A   # green
regular3=E0B15E   # yellow
regular4=7DA3B3   # blue
regular5=AC8ED0   # magenta
regular6=7FC9A8   # cyan
regular7=E5E9D8   # white
 
## bright (8-15)
bright0=626F51    # bright black
bright1=DB8267    # bright red
bright2=9FD88A    # bright green
bright3=E0B15E    # bright yellow
bright4=7DA3B3    # bright blue
bright5=AC8ED0    # bright magenta
bright6=7FC9A8    # bright cyan
bright7=F6F8EF    # bright white
 
selection-foreground=15170F
selection-background=9FD88A
urls=9FD88A

